name: meter_reading_app
description: "A Flutter application for automating water meter reading and billing for commercial buildings."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.9

  
  # UI
  cupertino_icons: ^1.0.6

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  bloc: ^8.1.4

  # Dependency Injection
  get_it: ^7.7.0

  # Network & API
  http: ^1.2.1
  dio: ^5.4.3+1
  internet_connection_checker: ^1.0.0+1

  # Local Storage
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Functional Programming
  dartz: ^0.10.1

  # Camera & QR Code
  camera: ^0.10.5+9
  mobile_scanner: ^5.1.1

  # Image Processing
  image_picker: ^1.1.2
  image: ^4.2.0
  path_provider: ^2.1.3
  path: ^1.9.0

  # OCR
  google_mlkit_text_recognition: ^0.15.0


  # PDF Generation
  pdf: ^3.10.8
  printing: ^5.12.0

  # Date & Time
  intl: ^0.19.0

  # Permissions
  permission_handler: ^11.3.1

  # Utils
  logger: ^2.3.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  # Linting
  flutter_lints: ^3.0.2

  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  build_runner: ^2.4.9

  # Code Generation
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/icon/logo_aquaflow.png
    - assets/icon/logo_aquaflow.svg
    - assets/icon/home.svg
    - assets/icon/scanner.svg
    - assets/icon/setting.svg

  # Fonts
  fonts:
     - family: Inter
       fonts:
       - asset: assets/fonts/Inter-VariableFont.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700

flutter_native_splash:
  color: "#0E2738" 
  image: assets/icon/logo_aquaflow.png
  
  android: true
  ios: true
  
  android_12:
    color: "#0E2738"
    image: assets/icon/logo_aquaflow.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo_aquaflow.png"

  min_sdk_android: 21
  adaptive_icon_background: "#0E2738"
  adaptive_icon_foreground: "assets/icon/logo_aquaflow.png"